#用户配置
# email为需要发送的邮箱
# citycode为城市代码，即中国天气网网址最后一串数字
# 示例：https://www.weather.com.cn/weather/101251201.shtml
# 其中101251021即城市代码
users:
  - email: 123456@qq.com # 邮箱地址
    citycode: 101251201 # 城市代码

# 邮箱配置
# service为邮箱服务商，如QQ，163
# user 为发送邮件的邮箱
# pass为邮箱专用密码
email_config:
  service: "QQ" #邮箱服务商
  auth:
    user: "123456@qq.com" #邮箱账号
    pass: "xxxxxx" #邮箱密码

#雨雪天气预警阈值，单位：小时
#若填10则获取10h内的天气，若出现雨雪天则警告
warn_num: 10

#天气指数显示个数
#若填5则邮件中显示五个天气指数提示
hint_num: 5

#天气指数显示配置，按顺序把需要的指数前的编号填入下方即可
hint_priority: [18, 27, 20]
#1. 路况指数  2. 晨练指数  3.夜生活指数  4.感冒指数  5.逛街指数  6.空气污染扩散条件指数
#7.旅游指数  8.舒适度指数  9.啤酒指数  10.划船指数  11.太阳镜指数  12.紫外线强度指数
#13.风寒指数  14.穿衣指数  15.放风筝指数  16.空调开启指数  17.钓鱼指数  18.晾晒指数
#19.洗车指数  20.心情指数  21.中暑指数  22.交通指数  23.约会指数  24.运动指数
#25.过敏指数  26.美发指数  27.雨伞指数  28.防晒指数  29.化妆指数  30.干燥指数

# 天气代码
wea:
  "00": "晴"
  "01": "多云"
  "02": "阴"
  "03": "阵雨"
  "04": "雷阵雨"
  "05": "雷阵雨伴有冰雹"
  "06": "雨夹雪"
  "07": "小雨"
  "08": "中雨"
  "09": "大雨"
  "10": "暴雨"
  "13": "阵雪"
  "14": "小雪"
  "15": "中雪"
  "16": "大雪"
  "17": "暴雪"

#指数代码
hints:
  - "lk_des_s"
  - "cl_des_s"
  - "nl_des_s"
  - "gm_des_s"
  - "gj_des_s"
  - "pl_des_s"
  - "tr_des_s"
  - "co_des_s"
  - "pj_des_s"
  - "hc_des_s"
  - "gl_des_s"
  - "uv_des_s"
  - "wc_des_s"
  - "ct_des_s"
  - "pk_des_s"
  - "ac_des_s"
  - "dy_des_s"
  - "ls_des_s"
  - "xc_des_s"
  - "xq_des_s"
  - "zs_des_s"
  - "jt_des_s"
  - "yh_des_s"
  - "yd_des_s"
  - "ag_des_s"
  - "mf_des_s"
  - "ys_des_s"
  - "fs_des_s"
  - "pp_des_s"
  - "gz_des_s"
