//https://d1.weather.com.cn/weather_index/101220505.html?_=1741414589148

var cityDZ = {
  weatherinfo: {
    city: "花山",
    cityname: "huashan",
    temp: "10",
    tempn: "7",
    weather: "晴转多云",
    wd: "东风转东南风",
    ws: "<3级转3-4级",
    weathercode: "d0",
    weathercoden: "n1",
    fctime: "202503080800",
  },
};

var dataSK = {
  nameen: "huashan",
  cityname: "花山",
  city: "101220505",
  temp: "13.7",
  tempf: "56.7",
  WD: "东风",
  wde: "E",
  WS: "2级",
  wse: "9km/h",
  SD: "42%",
  sd: "42%",
  qy: "1015",
  njd: "9km",
  time: "17:10",
  rain: "0",
  rain24h: "0",
  aqi: "79",
  aqi_pm25: "79",
  weather: "晴",
  weathere: "Sunny",
  weathercode: "d00",
  limitnumber: "",
  date: "03月08日(星期六)",
};

var dataZS = {
  zs: {
    date: "2025030811",
    lk_name: "路况指数",
    lk_hint: "干燥",
    lk_des_s: "天气较好，路面较干燥，路况较好。",
    cl_name: "晨练指数",
    cl_hint: "适宜",
    cl_des_s: "天气不错，空气清新。",
    nl_name: "夜生活指数",
    nl_hint: "较适宜",
    nl_des_s: "只要您稍作准备就可以放心外出。",
    gm_name: "感冒指数",
    gm_hint: "少发",
    gm_des_s: "无明显降温，感冒机率较低。",
    gj_name: "逛街指数",
    gj_hint: "适宜",
    gj_des_s: "这种好天气去逛街可使身心畅快放松。",
    pl_name: "空气污染扩散条件指数",
    pl_hint: "中",
    pl_des_s: "易感人群应适当减少室外活动。",
    tr_name: "旅游指数",
    tr_hint: "适宜",
    tr_des_s: "天气较好，可尽情地享受大自然的风光。",
    co_name: "舒适度指数",
    co_hint: "较舒适",
    co_des_s: "白天晴好，早晚偏凉，午后舒适。",
    pj_name: "啤酒指数",
    pj_hint: "较不适宜",
    pj_des_s: "有些凉意，少量饮用常温啤酒。",
    hc_name: "划船指数",
    hc_hint: "适宜",
    hc_des_s: "天气较好，适宜划船及嬉玩水上运动。",
    gl_name: "太阳镜指数",
    gl_hint: "必要",
    gl_des_s: "建议佩戴透射比为1级的遮阳镜",
    uv_name: "紫外线强度指数",
    uv_hint: "很强",
    uv_des_s: "涂擦SPF20以上，PA++护肤品，避强光。",
    wc_name: "风寒指数",
    wc_hint: "无",
    wc_des_s: "温度未达到风寒所需的低温，稍作防寒准备即可。",
    ct_name: "穿衣指数",
    ct_hint: "较冷",
    ct_des_s: "建议着厚外套加毛衣等服装。",
    pk_name: "放风筝指数",
    pk_hint: "适宜",
    pk_des_s: "好天气，放风筝可以舒展筋骨放松身心。",
    ac_name: "空调开启指数",
    ac_hint: "较少开启",
    ac_des_s: "体感舒适，不需要开启空调。",
    dy_name: "钓鱼指数",
    dy_hint: "适宜",
    dy_des_s: "适宜垂钓，愿您度过愉快垂钓时光。",
    ls_name: "晾晒指数",
    ls_hint: "适宜",
    ls_des_s: "天气不错，抓紧时机让衣物晒太阳吧。",
    xc_name: "洗车指数",
    xc_hint: "较不宜",
    xc_des_s: "风力较大，洗车后会蒙上灰尘。",
    xq_name: "心情指数",
    xq_hint: "好",
    xq_des_s: "好天气会带来一天的好心情。",
    zs_name: "中暑指数",
    zs_hint: "无中暑风险",
    zs_des_s: "天气舒适，对易中暑人群来说非常友善。",
    jt_name: "交通指数",
    jt_hint: "良好",
    jt_des_s: "气象条件良好，车辆可以正常行驶。",
    yh_name: "约会指数",
    yh_hint: "较适宜",
    yh_des_s: "不用担心天气来调皮捣乱而影响了兴致。",
    yd_name: "运动指数",
    yd_hint: "较适宜",
    yd_des_s: "气温较低，在户外运动请注意增减衣物。",
    ag_name: "过敏指数",
    ag_hint: "较易发",
    ag_des_s: "需注意远离过敏源，适当采取防护措施。",
    mf_name: "美发指数",
    mf_hint: "一般",
    mf_des_s: "建议选用防晒滋润型护发品或带遮阳帽。",
    ys_name: "雨伞指数",
    ys_hint: "不带伞",
    ys_des_s: "天气较好，不用带雨伞。",
    fs_name: "防晒指数",
    fs_hint: "极强",
    fs_des_s: "需涂擦SPF大于20，PA++，护肤品。",
    pp_name: "化妆指数",
    pp_hint: "防晒",
    pp_des_s: "请选用中性保湿型化妆品。",
    gz_name: "干燥指数",
    gz_hint: "干燥",
    gz_des_s:
      "气温偏高，空气干燥，皮肤水分流失较多，应预防可能出现的皮肤瘙痒等情况，涂抹高保湿补水的护肤品，不要穿紧身衣服。",
  },
};

var fc = {
  f: [
    {
      fa: "00",
      fb: "01",
      fc: "16",
      fd: "5",
      fe: "东风",
      ff: "东南风",
      fg: "<3级",
      fh: "3-4级",
      fk: "2",
      fl: "3",
      fm: "83.9",
      fn: "41.6",
      fi: "3/8",
      fj: "今天",
    },
    {
      fa: "01",
      fb: "02",
      fc: "14",
      fd: "7",
      fe: "东风",
      ff: "东南风",
      fg: "3-4级",
      fh: "3-4级",
      fk: "2",
      fl: "3",
      fm: "92.3",
      fn: "52.4",
      fi: "3/9",
      fj: "星期日",
    },
    {
      fa: "01",
      fb: "00",
      fc: "18",
      fd: "8",
      fe: "西南风",
      ff: "西南风",
      fg: "<3级",
      fh: "<3级",
      fk: "5",
      fl: "5",
      fm: "90.3",
      fn: "61.7",
      fi: "3/10",
      fj: "星期一",
    },
    {
      fa: "01",
      fb: "08",
      fc: "21",
      fd: "7",
      fe: "东风",
      ff: "东风",
      fg: "<3级",
      fh: "<3级",
      fk: "2",
      fl: "2",
      fm: "99.8",
      fn: "65.1",
      fi: "3/11",
      fj: "星期二",
    },
    {
      fa: "07",
      fb: "01",
      fc: "16",
      fd: "12",
      fe: "东风",
      ff: "东风",
      fg: "<3级",
      fh: "<3级",
      fk: "2",
      fl: "2",
      fm: "98",
      fn: "92",
      fi: "3/12",
      fj: "星期三",
    },
  ],
};

var wea = {
  "00": "晴",
  "01": "多云",
  "02": "阴",
  "03": "阵雨",
  "04": "雷阵雨",
  "05": "雷阵雨伴有冰雹",
  "06": "雨夹雪",
  "07": "小雨",
  "08": "中雨",
  "09": "大雨",
  10: "暴雨",
  13: "阵雪",
  14: "小雪",
  15: "中雪",
  16: "大雪",
  17: "暴雪",
};

var fxbm = {
  0: "微风",
  1: "东北风",
  2: "东风",
  3: "东南风",
  4: "南风",
  5: "西南风",
  6: "西风",
  7: "西北风",
  8: "北风",
  9: "旋转风",
};
